# Generated by Django 5.2.4 on 2025-08-02 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('headteacher', 'Head Teacher'), ('class_teacher', 'Class Teacher'), ('academic_teacher', 'Academic Teacher'), ('statistic_teacher', 'Statistic Teacher')], default='academic_teacher', max_length=20),
        ),
    ]
