# Generated by Django 5.2.4 on 2025-08-03 12:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='A brief, descriptive title for the notification.', max_length=255)),
                ('message', models.TextField(help_text='The full content of the notification.')),
                ('notification_type', models.CharField(choices=[('general', 'General Announcement'), ('alert', 'Urgent Alert'), ('event', 'Event Reminder'), ('action', 'Action Required'), ('holiday', 'Holiday Notice')], default='general', help_text='Categorize the notification (e.g., General, Urgent).', max_length=20)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, help_text='The date and time this notification becomes visible.')),
            ],
            options={
                'verbose_name': 'School Notification',
                'verbose_name_plural': 'School Notifications',
                'ordering': ['-published_date'],
            },
        ),
    ]
