# Generated by Django 5.2.4 on 2025-08-03 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_examination_subject_class_student_mark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='current_class',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='examination',
        ),
        migrations.AlterUniqueTogether(
            name='mark',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='mark',
            name='recorded_by',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='student',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='subject',
        ),
        migrations.DeleteModel(
            name='Class',
        ),
        migrations.DeleteModel(
            name='Examination',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Mark',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
