# Generated by Django 5.2.4 on 2025-08-02 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('year', models.IntegerField(default=2025)),
                ('class_teacher', models.OneToOneField(blank=True, limit_choices_to={'role': 'class_teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_class', to=settings.AUTH_USER_MODEL)),
                ('subjects', models.ManyToManyField(related_name='classes_assigned', to='students.subject')),
            ],
            options={
                'verbose_name_plural': 'Classes',
                'unique_together': {('name', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('academic_year', models.IntegerField()),
                ('term', models.CharField(choices=[('1', 'Term 1'), ('2', 'Term 2'), ('3', 'Term 3')], max_length=1)),
                ('classes_taking_exam', models.ManyToManyField(related_name='examinations', to='students.class')),
            ],
            options={
                'ordering': ['-academic_year', 'term', 'date', 'name'],
                'unique_together': {('name', 'academic_year', 'term')},
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('admission_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Graduated', 'Graduated'), ('Transferred', 'Transferred Out'), ('Suspended', 'Suspended')], default='Active', max_length=20)),
                ('current_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='students.class')),
            ],
            options={
                'ordering': ['current_class__name', 'first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(blank=True, null=True)),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.examination')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.subject')),
            ],
            options={
                'ordering': ['examination__academic_year', 'examination__term', 'student__current_class__name', 'student__first_name'],
                'unique_together': {('student', 'subject', 'examination')},
            },
        ),
    ]
