# Generated by Django 5.2.4 on 2025-08-02 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examination',
            name='name',
            field=models.CharField(choices=[('First Midterm Test', 'First Midterm Test'), ('First Term Examination', 'First Term Examination'), ('Second Midterm Test', 'Second Midterm Test'), ('Annual Examination', 'Annual Examination'), ('Mock Examination', 'Mock Examination')], max_length=255),
        ),
    ]
