# Generated by Django 5.2.4 on 2025-08-02 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_examination_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('poster', 'Poster'), ('announcement', 'Announcement'), ('link', 'Important Link'), ('other', 'Other Document')], default='announcement', max_length=20)),
                ('content', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='school_documents/')),
                ('external_url', models.URLField(blank=True, max_length=500, null=True)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'School Document',
                'verbose_name_plural': 'School Documents',
                'ordering': ['-published_date'],
            },
        ),
    ]
