# Generated by Django 5.2.4 on 2025-08-03 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_schooldocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooldocument',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description for the document.', null=True),
        ),
    ]
