# Generated by Django 5.2.4 on 2025-08-20 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_student_admission_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='has_attempted_exam',
            field=models.BooleanField(default=False),
        ),
    ]
