# Generated by Django 5.2.4 on 2025-08-22 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_student_has_attempted_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='graduation_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
