# Generated by Django 5.2.4 on 2025-10-10 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_student_graduation_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='admission_number',
            new_name='prem_number',
        ),
    ]
